import { FunctionsHttpError } from '@supabase/supabase-js'
import { supabase } from '../../../lib/supabase'

const PREVIEW_FUNCTION_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/preview-template`
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined

// A superset of every prop name a creator template might read. Templates built
// against the current scaffold use customMessage/photoUrls; older bundles use
// message/photos. Supplying both (plus musicUrl/customData) means a template
// reading `photos.length` or `photoUrls.length` always gets a defined array.
const PREVIEW_PROPS = {
  recipientName: 'Preview Recipient',
  senderName: 'Preview Sender',
  message: 'This is a preview of your template.',
  customMessage: 'This is a preview of your template.',
  photos: [] as string[],
  photoUrls: [] as string[],
  musicUrl: undefined as string | undefined,
  customData: {} as Record<string, unknown>,
  previewMode: true,
}

// Stop the bundle source from prematurely closing the inline <script> tag.
function escapeForScript(source: string): string {
  return source.replace(/<\/(script)/gi, '<\\/$1')
}

/**
 * Builds the self-diagnosing preview HTML in the browser (it used to be
 * generated by the edge function, but the Edge Runtime forces text/plain on HTML
 * responses). React + ReactDOM load from the CDN, a `require` shim maps the
 * bundle's react/jsx-runtime import onto the CDN globals, an error boundary and
 * an on-screen status strip surface any failure, and the bundle is mounted with
 * PREVIEW_PROPS. This string is wrapped in a same-origin Blob so the iframe
 * renders it as real text/html.
 */
function buildPreviewHtml(bundleSource: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Template preview</title>
<style>
  html,body{margin:0;padding:0;height:100%;width:100%;}
  #root{min-height:100%;width:100%;}
  #root-placeholder{padding:24px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
    font-size:13px;color:#475569;}
  #preview-status{position:fixed;left:0;right:0;bottom:0;z-index:2147483647;max-height:40%;
    overflow:auto;margin:0;padding:8px 12px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
    font-size:12px;line-height:1.5;color:#e2e8f0;background:rgba(15,23,42,0.92);white-space:pre-wrap;}
  #preview-status.error{color:#fecaca;background:rgba(69,10,10,0.95);}
</style>
<!-- React + ReactDOM globals BEFORE the bundle runs. Development builds so any
     render-time error is human-readable. No crossorigin attribute: CORS-mode
     fetches can fail silently in the opaque-origin sandboxed iframe. -->
<script src="https://unpkg.com/react@18/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
<script>
  function logStatus(message, isError) {
    var box = document.getElementById('preview-status');
    if (!box) return;
    box.textContent += (box.textContent ? '\\n' : '') + message;
    if (isError) box.className = 'error';
  }
  window.addEventListener('error', function (event) {
    logStatus('✗ ' + ((event.error && event.error.message) || event.message || 'Unknown error'), true);
  });
  window.addEventListener('unhandledrejection', function (event) {
    logStatus('✗ promise rejected: ' + ((event.reason && event.reason.message) || event.reason), true);
  });

  // The creator bundle is an esbuild IIFE with react/react-dom external, so it
  // calls require("react/jsx-runtime") at runtime. esbuild's shim uses the global
  // require when one exists; provide it, mapping module names onto the CDN
  // globals. Without this the IIFE throws and never defines WishCraftTemplate.
  window.require = function (name) {
    var R = window.React;
    if (name === 'react') return R;
    if (name === 'react-dom' || name === 'react-dom/client') return window.ReactDOM;
    if (name === 'react/jsx-runtime' || name === 'react/jsx-dev-runtime') {
      var jsx = function (type, config, maybeKey) {
        var props = Object.assign({}, config);
        if (maybeKey !== undefined) props.key = maybeKey;
        return R.createElement(type, props);
      };
      return { jsx: jsx, jsxs: jsx, jsxDEV: jsx, Fragment: R.Fragment };
    }
    throw new Error('Module not available in preview: ' + name);
  };
</script>
</head>
<body>
<div id="root"><div id="root-placeholder">Loading preview…</div></div>
<pre id="preview-status"></pre>
<script>
  logStatus(window.React ? 'React ✓' : 'React ✗ (CDN did not load)', !window.React);
  logStatus(window.ReactDOM ? 'ReactDOM ✓' : 'ReactDOM ✗ (CDN did not load)', !window.ReactDOM);
</script>

<!-- The template bundle, inlined. It assigns the global WishCraftTemplate. -->
<script>${escapeForScript(bundleSource)}</script>

<!-- Mount AFTER the bundle has run, so WishCraftTemplate is defined. -->
<script>
  (function () {
    var root = document.getElementById('root');
    var props = ${JSON.stringify(PREVIEW_PROPS)};

    var exported = window.WishCraftTemplate;
    if (!exported) {
      logStatus('bundle ✗ — WishCraftTemplate global was not defined', true);
      return;
    }
    logStatus('bundle: WishCraftTemplate defined ✓');

    var Template = exported.default != null ? exported.default : exported;
    if (typeof Template !== 'function') {
      logStatus('component ✗ — bundle did not export a renderable component (got ' + typeof Template + ')', true);
      return;
    }
    logStatus('component: function ✓');

    function PreviewBoundary(props) { React.Component.call(this, props); this.state = { error: null }; }
    PreviewBoundary.prototype = Object.create(React.Component.prototype);
    PreviewBoundary.getDerivedStateFromError = function (error) { return { error: error }; };
    PreviewBoundary.prototype.componentDidCatch = function (error) {
      logStatus('render ✗ — ' + (error && error.message ? error.message : String(error)), true);
    };
    PreviewBoundary.prototype.render = function () {
      if (this.state.error) {
        return React.createElement('pre', {
          style: { padding: 20, margin: 0, color: '#b91c1c', background: '#fff',
            fontFamily: 'ui-monospace,Menlo,monospace', fontSize: 13, whiteSpace: 'pre-wrap' },
        }, 'Template render failed:\\n' + (this.state.error.message || String(this.state.error)));
      }
      return React.createElement(Template, props);
    };

    try {
      var placeholder = document.getElementById('root-placeholder');
      if (placeholder) placeholder.remove();
      ReactDOM.createRoot(root).render(React.createElement(PreviewBoundary, null));
      logStatus('mounted ✓');
    } catch (err) {
      logStatus('mount ✗ — ' + (err && err.message ? err.message : String(err)), true);
    }
  })();
</script>
</body>
</html>`
}

export type SubmissionStatus = 'pending' | 'approved' | 'rejected' | 'active'
export type ReviewAction = 'approve' | 'reject'

export interface TemplateSubmissionTheme {
  primaryColor: string
  backgroundColor: string
  surfaceColor: string
  textColor: string
  fontHeading: string
}

export interface TemplateSubmissionConfig {
  name: string
  slug: string
  category: string
  price: number
  sdkVersion: string
  fields: unknown[]
  theme: TemplateSubmissionTheme
}

export interface TemplateSubmission {
  id: string
  creator_id: string
  config: TemplateSubmissionConfig
  status: SubmissionStatus
  bundle_path: string | null
  preview_path: string | null
  rejection_note: string | null
  submitted_at: string
  reviewed_at: string | null
  reviewed_by: string | null
}

interface ReviewResponse {
  success?: boolean
  templateId?: string
  error?: string
}

interface SignPreviewResponse {
  signedUrl?: string
  error?: string
}

export async function fetchSubmissions(status: SubmissionStatus): Promise<TemplateSubmission[]> {
  const { data, error } = await supabase
    .from('template_submissions')
    .select('id, creator_id, config, status, bundle_path, preview_path, rejection_note, submitted_at, reviewed_at, reviewed_by')
    .eq('status', status)
    .order('submitted_at', { ascending: false })

  if (error) throw new Error(error.message)
  return (data ?? []) as TemplateSubmission[]
}

/**
 * Pending bundles live in the private `templates-pending` bucket, which the
 * browser cannot read directly. The preview is assembled entirely client-side:
 *
 *  1. `sign-preview` authenticates the admin (via the session JWT that
 *     supabase.functions.invoke attaches) and returns a short-lived, self-
 *     expiring signed URL for the bundle. No admin JWT is ever placed in a URL.
 *  2. `preview-template` proxies that signed URL and returns the raw bundle JS
 *     with permissive CORS (the Edge Runtime would force text/plain on HTML, so
 *     the function returns JS instead).
 *  3. We build the preview HTML here and wrap it in a same-origin Blob URL, which
 *     the sandboxed iframe renders as real text/html.
 *
 * Returns a `blob:` URL — the caller must `URL.revokeObjectURL` it when done.
 */
export async function createSubmissionPreviewUrl(submission: TemplateSubmission): Promise<string> {
  const { data, error } = await supabase.functions.invoke<SignPreviewResponse>('sign-preview', {
    body: { submissionId: submission.id },
  })

  if (error) {
    if (error instanceof FunctionsHttpError) {
      const detail = (await error.context.json().catch(() => null)) as SignPreviewResponse | null
      throw new Error(detail?.error ?? error.message)
    }
    throw new Error(error.message)
  }
  if (data?.error) throw new Error(data.error)
  if (!data?.signedUrl) throw new Error('Could not create a preview URL')

  // Fetch the raw bundle through preview-template (CORS-friendly proxy of the
  // signed URL). The response Content-Type is irrelevant — we read it as text.
  const bundleEndpoint = new URL(PREVIEW_FUNCTION_URL)
  bundleEndpoint.searchParams.set('signedUrl', data.signedUrl)
  if (SUPABASE_ANON_KEY) bundleEndpoint.searchParams.set('apikey', SUPABASE_ANON_KEY)

  const bundleResponse = await fetch(bundleEndpoint.toString())
  if (!bundleResponse.ok) {
    throw new Error(`Could not load template bundle (status ${bundleResponse.status})`)
  }
  const bundleSource = await bundleResponse.text()

  const html = buildPreviewHtml(bundleSource)
  const blob = new Blob([html], { type: 'text/html' })
  return URL.createObjectURL(blob)
}

export async function reviewSubmission(
  submissionId: string,
  action: ReviewAction,
  rejectionNote?: string,
): Promise<ReviewResponse> {
  const { data, error } = await supabase.functions.invoke<ReviewResponse>('review-template', {
    body: { submissionId, action, rejectionNote },
  })

  if (error) {
    // A handled non-2xx response surfaces here as a FunctionsHttpError whose
    // `message` is the opaque "Edge Function returned a non-2xx status code".
    // The real reason (e.g. "Failed to read submitted preview") is in the JSON
    // body carried by `context` — pull it out so the admin sees what happened.
    if (error instanceof FunctionsHttpError) {
      const detail = (await error.context.json().catch(() => null)) as ReviewResponse | null
      throw new Error(detail?.error ?? error.message)
    }
    throw new Error(error.message)
  }
  if (data?.error) throw new Error(data.error)
  return data ?? {}
}
